spring.application.name=conde-finance-api
server.port=8080

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}

#spring.jpa.show-sql=true
#spring.jpa.hibernate.ddl-auto=update

api.security.token.secret=${JWT_SECRET:conde-finance-secret-key}

springdoc.swagger-ui.use-root-path=true
server.forward-headers-strategy=framework
springdoc.swagger-ui.path=/swagger-ui.html

app.cors.allowed-origins=https://condefinance.marcoscondejr.com.br/,http://localhost:*