INSERT INTO bank (code, name) VALUES
  ('001', 'Banco do Brasil S.A.'),
  ('003', 'Banco da Amazônia S.A.'),
  ('004', 'Banco do Nordeste do Brasil S.A.'),
  ('007', 'Banco Nacional de Desenvolvimento Econômico e Social'),
  ('021', 'Banco do Estado do Espírito Santo S.A.'),
  ('025', 'Banco Alfa S.A.'),
  ('033', 'Banco Santander (Brasil) S.A.'),
  ('036', 'Banco Bradesco BBI S.A.'),
  ('037', 'Banco do Estado do Pará S.A.'),
  ('041', 'Banco do Estado do Rio Grande do Sul S.A.'),
  ('047', 'Banco do Estado de Sergipe S.A.'),
  ('070', 'BRB - Banco de Brasília S.A.'),
  ('077', 'Banco Inter S.A.'),
  ('084', 'Uniprime Norte do Paraná'),
  ('085', 'Cooperativa Central de Crédito Urbano'),
  ('097', 'Credisis Central'),
  ('104', 'Caixa Econômica Federal'),
  ('107', 'Banco BOCOM BBM S.A.'),
  ('121', 'Agibank S.A.'),
  ('136', 'Unicred do Brasil'),
  ('184', 'Banco Itaú BBA S.A.'),
  ('197', 'Stone Pagamentos S.A.'),
  ('208', 'Banco BTG Pactual S.A.'),
  ('212', 'Banco Original S.A.'),
  ('218', 'Banco BS2 S.A.'),
  ('237', 'Banco Bradesco S.A.'),
  ('241', 'Banco Clássico S.A.'),
  ('260', 'Nu Pagamentos S.A. (Nubank)'),
  ('290', 'PagSeguro Internet S.A.'),
  ('318', 'Banco BMG S.A.'),
  ('323', 'Mercado Pago'),
  ('330', 'Banco Bari S.A.'),
  ('335', 'Banco Digio S.A.'),
  ('336', 'Banco C6 S.A.'),
  ('341', 'Itaú Unibanco S.A.'),
  ('352', 'Banco Santander Brasil S.A.'),
  ('364', 'Gerencianet Pagamentos do Brasil'),
  ('380', 'PicPay Serviços S.A.'),
  ('389', 'Banco Mercantil do Brasil S.A.'),
  ('403', 'Cora Sociedade de Crédito Direto S.A.'),
  ('422', 'Banco Safra S.A.'),
  ('453', 'Banco Rural S.A.'),
  ('456', 'Banco MUFG Brasil S.A.'),
  ('464', 'Banco Sumitomo Mitsui Brasileiro S.A.'),
  ('473', 'Banco Caixa Geral Brasil S.A.'),
  ('477', 'Citibank N.A.'),
  ('505', 'Banco Credit Suisse Brasil S.A.'),
  ('600', 'Banco Luso Brasileiro S.A.'),
  ('604', 'Banco Industrial do Brasil S.A.'),
  ('612', 'Banco Guanabara S.A.'),
  ('613', 'Banco Pecúnia S.A.'),
  ('623', 'Banco Pan S.A.'),
  ('626', 'Banco C6 Consignado S.A.'),
  ('633', 'Banco Rendimento S.A.'),
  ('637', 'Banco Sofisa S.A.'),
  ('643', 'Banco Pine S.A.'),
  ('652', 'Itaú Unibanco Holding S.A.'),
  ('653', 'Banco Indusval S.A.'),
  ('654', 'Banco A.J. Renner S.A.'),
  ('655', 'Banco Votorantim S.A.'),
  ('707', 'Banco Daycoval S.A.'),
  ('712', 'Banco Ourinvest S.A.'),
  ('735', 'Banco Neon S.A.'),
  ('739', 'Banco Cetelem S.A.'),
  ('740', 'Banco Barclays S.A.'),
  ('741', 'Banco Ribeirão Preto S.A.'),
  ('743', 'Banco Semear S.A.'),
  ('745', 'Banco Citibank S.A.'),
  ('746', 'Banco Modal S.A.'),
  ('747', 'Banco Rabobank International Brasil S.A.'),
  ('748', 'Banco Cooperativo Sicredi S.A.'),
  ('752', 'Banco BNP Paribas Brasil S.A.'),
  ('756', 'Banco Cooperativo do Brasil S.A. - BANCOOB')
    ON CONFLICT (code) DO NOTHING;